name: Generate terraform docs

# on:
#   - pull_request
on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        module: [instance, vcn, compartment]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: ./modules/${{ matrix.module }}
        output-file: README.md
        output-method: inject
        git-push: "true"